language: scala
scala:
  - "2.11.8"
jdk:
  - oraclejdk8

script: sbt clean scalafmtTest compile:scalastyle coverage test:scalastyle
branches:
  only:
    - master

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete